### ISSUE TITLE
Artifacts is expired.

### ISSUE THREAD

**Issue by kiyotaka4946g** [xiupos/android-skk#3]
GitHub ActionsのArtifactsがexpiredによりダウンロードできません。
自前でのビルドには成功、動作自体も問題ありませんが、ダウンロードできる、あるいはせめてビルド方法を明記してある方が良いかと思います。

**Comment by xiupos** [comment]
[README.md](https://github.com/xiupos/android-skk/commit/4ec3dfd59e5bce7abc4840736d4f5484c567d432)を更新しました。ご指摘ありがとうございます。
